### ISSUE TITLE
EventSystem not running

### ISSUE THREAD

**Issue by SnupW** [TWLan/Issues#114]
Sometimes i get this message:
EventSystem not running

Please make sure the eventsystem is running!
![u8pzyys](https://cloud.githubusercontent.com/assets/16511254/12071989/3fb2f990-b0d2-11e5-9f68-78d14726aa8c.png)
![47r3vuv](https://cloud.githubusercontent.com/assets/16511254/12072011/12f7caaa-b0d4-11e5-86e9-156167de645b.png)

**Comment by steffengy** [comment]
Seems like the eventsystem might be crashing there.
Could you check if your application eventlog contains any Application Errors?

Something like 
http://blogs.msdn.com/cfs-filesystemfile.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-37-14-metablogapi/7360.clip_5F00_image001_5F00_7BEE1C16.png]

?

**Comment by SnupW** [comment]
![opp5udf](https://cloud.githubusercontent.com/assets/16511254/12072236/9c0e12f0-b0dd-11e5-8dd2-015fb5df5f80.png)
![qh3rgdi](https://cloud.githubusercontent.com/assets/16511254/12072232/6e6c9bbe-b0dd-11e5-86ef-a8311e08cd80.png)

**Comment by steffengy** [comment]
seems like your TWLan database files somehow got damaged. (I cannot say whether its a general problem that the launcher doesn't terminate it properly but I think due to the commonness of the error it's unlikely)

**Comment by mapbug** [comment]
I have nearly the same Problem. 
what can I do?

MySQL:
2016-02-27 10:56:10 9076 [Note] mysql\bin\mysqld (mysqld 10.1.6-MariaDB) starting as process 8668 ...
EventSystem:
Exception:Activation returned error: Invalid request data

#0 Y:\Downloads\TWLAN\TWLan-win32\htdocs\index.php(3): TWLan\TWLan::run()
#1 {main}EventSystem: Process has died [0]

edit: I tried DsLan_v1.4  and it works. but I want the newest Version.

edit2: I prefer german language

**Comment by vERKE** [comment]
I have the same problem:

MySQL:
2017-05-28 18:58:03 9380 [Note] mysql\bin\mysqld (mysqld 10.1.6-MariaDB) starting as process 6532 ...
EventSystem:
Activation failed Connection Error:  (0)<br />
Exception:Could not activate the TWLan... Please try again latern
#0 C:\TWLan-win32\htdocs\index.php(3): TWLan\TWLan::run()
#1 {main}EventSystem: Process has died [0]

**Comment by Siguza** [comment]
@vERKE The activation server was down. Should be resolved now.
